# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout AutoPlug-Client
      uses: actions/checkout@master
      with:
        repository: 'Osiris-Team/AutoPlug-Client'
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14

    - name: Maven - Create jar
      run: mvn -B clean package --file pom.xml
      
      #This will delete the workflow-cache folder if exists, create a new one and copy AutoPlug.jar into it
    - name: Copy jar to workflow-cache dir
      run: |
       rm -rf workflow-cache
       mkdir -p workflow-cache
       cp target/AutoPlug.jar workflow-cache
      
    - name: Add and confirm update
      run: |
        git config --local user.email "osiris_support@pm.me"
        git config --local user.name "GitHub Action"
        git add workflow-cache/AutoPlug.jar
        git commit -m "Updated to latest beta-build" -a
      
    - name: Push/Upload update
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      
      #We also want to have the jar at our Releases repo
    - name: Checkout AutoPlug-Releases
      uses: actions/checkout@master
      with:
        repository: 'Osiris-Team/AutoPlug-Releases'
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        
      #Downloads the jar we uploaded 1sec ago to the AutoPlug-Client repo
    - name: Download jar
      run: |
        rm -rf beta-builds
        mkdir beta-builds
        wget -O beta-builds/AutoPlug.jar "https://github.com/Osiris-Team/AutoPlug-Client/raw/master/workflow-cache/AutoPlug.jar"
      
    - name: Add and confirm update
      run: |
        git config --local user.email "osiris_support@pm.me"
        git config --local user.name "GitHub Action"
        git add beta-builds/AutoPlug.jar
        git commit -m "Updated to latest beta-build" -a
      
    - name: Push/Upload update
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'master'
        force: true
        repository: 'Osiris-Team/AutoPlug-Releases'

